### ISSUE TITLE
error on launching

### ISSUE THREAD

**Issue by Yaksinikos** [RimWorldMod/Tech-Advancing#22]
[GistLog](https://gist.github.com/Translator5/21d84728df84354ccfc4fbfac9356d72)

On loading savegame.

**Comment by GHXX** [comment]
Can you paste the full output log please?
Something during mod init is interfering with techadvancing

**Comment by Yaksinikos** [comment]
actually not,
may this mod conflicts with something like ResearchPal or WorkTab, RimHUD ... ? do you have a list of mods that conflict?

**Comment by GHXX** [comment]
overlapping interaction spots possibly, but the full output log would help, because someone had a similar issue and multiple mods were failing initialization, which is likely also happening here.

The guy said he removed overlapping interaction spots, and installed hugslib.
Techadvancing however shouldnt require hugslib. so something is screwing with it.

**Comment by Yaksinikos** [comment]
I use the latest HugsLib v. from GitHub.
Also - whats about SimpleSidearms, Ride&Gun - may conflicting mods?

**Comment by GHXX** [comment]
I dont know, you could try to remove them, but the output log should contain useful info....

**Comment by GHXX** [comment]
Have you made any progress?
I am curious what might be causing it

**Comment by GHXX** [comment]
Closing this one due to inactivity. Likely a constructor of another mod is failing during game boot. Feel free to comment if you got any further information.
